<ul>
	<li>Version 0.4 - 17 December 2012<br />
		<ul>
			<li>Internal moving of code parts for support of lazy loading;</li>
			<li>Allow usage in 1.11 environment.</li>
		</ul>
	</li>
	<li>Version 0.3 - 15 January 2012<br />
		<ul>
			<li>Allow usage in 1.10 environment.</li>
		</ul>
	</li>
	<li>Version 0.2 - 6 August 2011.<br />
		<ul>
			<li>No discount calculated if maximum redemptions for code was not greater then zero.</li>
		</ul>
	</li>
	<li>Version 0.1 - 29 July 2011.<br />
		<ul>
			<li>Initial Release.</li>
		</ul>
	</li>
</ul>